kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol01
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: 51.20.78.207
    path: /srv/nfs/vol01
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
